version: 2
updates:
  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: "Source/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "npm"
    # location of package manifests
    directory: "Source/Services/RPSLS.NodePlayer.Api/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "pip"
    # location of package manifests
    directory: "Source/Services/RPSLS.PythonPlayer.Api/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "pip"
    # location of package manifests
    directory: "Source/Functions/RPSLS.Python.Api/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "maven"
    # location of package manifests
    directory: "Source/Services/RPSLS.JavaPlayer.Api/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "composer"
    # location of package manifests
    directory: "Source/Services/RPSLS.PHPPlayer.Api/src/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
