apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ template "rpsls-web.name" . }}
    chart: {{ template "rpsls-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.uploaderPort }}
      targetPort: uploader
      protocol: TCP
      name: uploader
  selector:
    app: {{ template "rpsls-web.name" . }}
    release: {{ .Release.Name }}
